version: 1
receiverHealth:
  url: http://receiver/receiver/health
  service: receiver
storageHealth:
  url: http://storage/storage/health
  service: storage
processingHealth:
  url: http://processing/processing/health
  service: processing
auditHealth:
  url: http://audit_log/audit_log/health
  service: audit
scheduler:
  period_sec: 20
timeout: 5
