version: 1
datastore:
  user:
  password:
  # hostname: localhost
  hostname: ec2-3-87-61-46.compute-1.amazonaws.com
  port: 3306
  db: inventory
events:
  hostname: ec2-3-87-61-46.compute-1.amazonaws.com
  port: 9092
  topic: events
