version: 1
expenseEvent:
  url: http://localhost:8090/expense
revenueEvent:
  url: http://localhost:8090/revenue
events:
  hostname: ec2-3-86-224-93.compute-1.amazonaws.com
  port: 9092
  topic: events
