version: 1
datastore:
  user: mysql_user
  password: SecuRe_pwd1
  # hostname: localhost
  hostname: ec2-3-86-224-93.compute-1.amazonaws.com
  port: 3306
  db: inventory
events:
  hostname: ec2-3-86-224-93.compute-1.amazonaws.com
  port: 9092
  topic: events
